### ISSUE TITLE
Support for showing PURL and CPE in the summary table

### ISSUE THREAD

**Issue by alcroito** [anthonyharrison/sbom2doc#4]
Hi,

Thanks for writing this tool, it greatly helps to quickly visualize an SBOMs document content.

I was wondering if it would be possible to add a feature to display one more table that lists the package's PURL and CPE values?

**Comment by anthonyharrison** [comment]
@alcroito Thanks for the suggestion. 

The PURL value is already used to show the package ecosystem and the data in the CPE is used for supplier information. Are you suggesting that the full PURL and CPE values are shown for each package?

**Comment by alcroito** [comment]
Indeed. That it is my suggestion.

**Comment by alcroito** [comment]
I pushed a PR in case that's something you are open to adding.

https://github.com/anthonyharrison/sbom2doc/pull/5
